# Generated by Django 5.0 on 2025-11-12 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del rol')),
                ('puede_crear_asignatura', models.BooleanField(default=False, verbose_name='Puede crear asignaturas')),
                ('puede_editar_asignatura', models.BooleanField(default=False, verbose_name='Puede editar asignaturas')),
                ('puede_eliminar_asignatura', models.BooleanField(default=False, verbose_name='Puede eliminar asignaturas')),
                ('puede_crear_tarea', models.BooleanField(default=False, verbose_name='Puede crear tareas')),
                ('puede_editar_tarea', models.BooleanField(default=False, verbose_name='Puede editar tareas')),
                ('puede_eliminar_tarea', models.BooleanField(default=False, verbose_name='Puede eliminar tareas')),
                ('puede_calificar_tarea', models.BooleanField(default=False, verbose_name='Puede calificar tareas')),
                ('puede_ver_todas_calificaciones', models.BooleanField(default=False, verbose_name='Puede ver todas las calificaciones')),
                ('puede_entregar_tarea', models.BooleanField(default=False, verbose_name='Puede entregar tareas')),
                ('recibe_notificacion_estado_mensual', models.BooleanField(default=False, verbose_name='Recibe notificación de estado mensual')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superusuario')),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de recuperación')),
                ('token_recuperacion_expira', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Users.role', verbose_name='Rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
