# Generated by Django 5.0 on 2025-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la asignatura')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de la asignatura')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignaturas',
                'permissions': [('crear_asignatura', 'Puede crear asignaturas'), ('editar_asignatura', 'Puede editar asignaturas'), ('desactivar_asignatura', 'Puede activar o desactivar asignaturas'), ('asignar_docente_asignatura', 'Puede asignar docentes a asignaturas'), ('ver_asignaturas_campus', 'Puede ver todas las asignaturas del campus')],
            },
        ),
        migrations.CreateModel(
            name='CalificacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota numérica de la entrega.', max_digits=5, verbose_name='Nota')),
                ('retroalimentacion_docente', models.TextField(blank=True, null=True, verbose_name='Retroalimentación del docente')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de calificación')),
                ('estado_calificacion', models.CharField(default='CALIFICADA', help_text='Ej: CALIFICADA, REVISIÓN, ANULADA', max_length=50, verbose_name='Estado de calificación')),
            ],
            options={
                'verbose_name': 'Calificación de tarea',
                'verbose_name_plural': 'Calificaciones de tareas',
                'db_table': 'calificaciones_tareas',
                'permissions': [('calificar_tarea', 'Puede calificar tareas de estudiantes'), ('editar_calificacion_tarea', 'Puede editar calificaciones de tareas'), ('ver_calificaciones_asignatura', 'Puede ver calificaciones por asignatura'), ('ver_calificaciones_propias', 'Puede ver sus propias calificaciones')],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('comentarios_estudiante', models.TextField(blank=True, null=True, verbose_name='Comentarios del estudiante')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('estado_entrega', models.CharField(default='ENTREGADA', help_text='Ej: ENTREGADA, ATRASADA, RECHAZADA, PENDIENTE_REVISION', max_length=50, verbose_name='Estado de entrega')),
            ],
            options={
                'verbose_name': 'Entrega de tarea',
                'verbose_name_plural': 'Entregas de tareas',
                'db_table': 'entregas_tareas',
                'permissions': [('entregar_tarea', 'Puede registrar entregas de tareas'), ('ver_entregas_asignatura', 'Puede ver entregas de tareas por asignatura')],
            },
        ),
        migrations.CreateModel(
            name='InscripcionAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
            ],
            options={
                'verbose_name': 'Inscripción en asignatura',
                'verbose_name_plural': 'Inscripciones en asignaturas',
                'db_table': 'inscripciones_asignaturas',
                'permissions': [('gestionar_inscripciones_asignaturas', 'Puede gestionar inscripciones en asignaturas'), ('ver_inscripciones_asignaturas', 'Puede ver inscripciones en asignaturas')],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del período')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
                'db_table': 'periodos_academicos',
                'permissions': [('gestionar_periodos_academicos', 'Puede gestionar períodos académicos')],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('peso_porcentual', models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución al promedio final de la asignatura (0–100).', max_digits=5, verbose_name='Peso porcentual')),
                ('tipo_tarea', models.CharField(choices=[('TAREA', 'Tarea'), ('EXAMEN', 'Examen'), ('QUIZ', 'Quiz'), ('PROYECTO', 'Proyecto')], default='TAREA', max_length=20, verbose_name='Tipo de tarea')),
            ],
            options={
                'verbose_name': 'Tarea / Evaluación',
                'verbose_name_plural': 'Tareas / Evaluaciones',
                'db_table': 'tareas',
                'ordering': ['fecha_vencimiento'],
                'permissions': [('crear_tarea', 'Puede crear tareas y exámenes'), ('editar_tarea', 'Puede editar tareas y exámenes'), ('eliminar_tarea', 'Puede eliminar tareas y exámenes'), ('publicar_tarea', 'Puede publicar tareas y exámenes a estudiantes'), ('ver_tareas_asignatura', 'Puede ver las tareas de sus asignaturas')],
            },
        ),
    ]
