# Generated by Django 5.0 on 2025-11-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academico', '0001_initial'),
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='docente_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas_dictadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente responsable'),
        ),
        migrations.AddField(
            model_name='calificaciontarea',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_tareas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='archivo_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asociadas', to='Base.datoarchivo', verbose_name='Archivo de entrega'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='inscripcionasignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Academico.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='inscripcionasignatura',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_asignaturas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='Academico.periodoacademico', verbose_name='Período académico'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Academico.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='Academico.tarea', verbose_name='Tarea'),
        ),
        migrations.AddField(
            model_name='calificaciontarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='Academico.tarea', verbose_name='Tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionasignatura',
            unique_together={('asignatura', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='entregatarea',
            unique_together={('tarea', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='calificaciontarea',
            unique_together={('tarea', 'estudiante')},
        ),
    ]
