# Generated by Django 5.0 on 2025-11-21 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('reset_password_token', models.CharField(blank=True, max_length=200, null=True)),
                ('reset_password_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activation_token', models.CharField(blank=True, max_length=200, null=True)),
                ('activation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'permissions': [('gestionar_usuarios', 'Puede gestionar usuarios (crear, editar, bloquear)'), ('gestionar_roles_permisos', 'Puede gestionar roles y permisos del sistema'), ('cambiar_password_propio', 'Puede cambiar su propia contraseña'), ('forzar_reset_password_usuarios', 'Puede forzar reset de contraseña de otros usuarios'), ('recibir_notificacion_estado_mensual', 'Puede recibir reporte mensual de desempeño académico')],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash de contraseña anterior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Contraseña',
                'verbose_name_plural': 'Historial de Contraseñas',
                'db_table': 'usuarios_password_history',
                'ordering': ['-creado'],
            },
        ),
    ]
